### ISSUE TITLE
[Fix] 데이터 전달 오류 수정

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#147]
## 🛠 Issue
데이터 전달 오류 수정

## 📝 To-do

- [x] LoginEntity의 isMatch 값 전달하기
- [x] 로그아웃, 회원탈퇴 시 로그인뷰로 이동
- [x] CollectionViewCell 새로고침 오류 수정
