### ISSUE TITLE
[Chore] QA 반영

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#155]
## 🛠 Issue
QA 반영

## 📝 To-do
- [x] AssignView 레이아웃 수정
- [x] Archiving Section Cell 햅틱 넣기
- [x] 이미지 에셋 수정
- [x] AssignView se 기기대응
- [x] EntryView 버튼 ui 수정
