### ISSUE TITLE
[Chore] QA 반영

### ISSUE THREAD

**Issue by 0lynny** [Team-Umbba/Umbba-iOS#157]
## 🛠 Issue

- QA 반영

## 📝 To-do

- [x]  유저 정보 타이틀 변경
- [x] WritePopUP에 숫자만 미적용
- [x] 뷰 누르면 내려가게 없애기
- [ ] Detail 서버통신 분기처리
