### ISSUE TITLE
[Chore] QA 반영 

### ISSUE THREAD

**Issue by yujin-00** [Team-Umbba/Umbba-iOS#173]
## 🛠 Issue

- 텍스트상자를 눌러도 답변하기 뷰로 넘어갈 수 있도록
- 새벽, 아침, 낮, 저녁, 밤 워딩 매칭 오류
## 📝 To-do

- [x] UIView에 제스처 넣어주기
- [x] placeholder 문구 변경하기
- [x] 교신 공지 뷰에서 시간 형식 오류 수정하기
