### ISSUE TITLE
[Feat] QA 및 피드백 반영

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#176]
## 🛠 Issue
QA 및 피드백 반영

## 📝 To-do
- [x] 아카이빙 뷰 header 고정시키기
- [x] ListView -> DetailView로 갈때 루트 뷰컨 변경
- [x] 메인 화면, 초대코드 화면 텍스트 수정
