### ISSUE TITLE
[Feat] 엔딩뷰 UI 구현

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#179]
## 🛠 Issue
엔딩뷰 UI 구현

## 📝 To-do
- [x] 엔딩뷰 UI 구현
- [x] 버튼 클릭시 각 화면 연결
- [x] 뒤로가기 버튼 화면 전환

**Comment by kj9470** [comment]
빨리 구현해주세용 ㅎㅎ
