### ISSUE TITLE
[Fix] 수정 사항 반영

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#186]
## 🛠 Issue
수정 사항 반영

## 📝 To-do

- [x] 로그인 버튼 ui 변경
- [x] 엔딩페이지 연결종료하기 버튼 클릭 로직 수정
- [x] 아카이빙 -> 디테일 뷰 전환 방법 수정
