### ISSUE TITLE
[Feat] 설정 테이블뷰 섹션 추가

### ISSUE THREAD

**Issue by yujin-00** [Team-Umbba/Umbba-iOS#29]
## 🛠 Issue

- 설정 테이블뷰 "계정 관리" 섹션 추가

## 📝 To-do

- [x] 섹션 두개 만들기
- [x] "계정 관리" 셀 만들기
- [x] 클릭 이벤트 추가하기
