### ISSUE TITLE
[Feat] 팝업뷰 구현

### ISSUE THREAD

**Issue by 0lynny** [Team-Umbba/Umbba-iOS#33]
## 🛠 Issue

- 답변 작성 취소 팝업 UI
- 답변 저장 팝업 UI
- 회원탈퇴 팝업 UI

## 📝 To-do

- [ ] 답변 작성 취소 팝업 UI
- [ ] 답변 저장 팝업 UI
- [ ] 회원탈퇴 팝업 UI
