### ISSUE TITLE
[Chore] 시작 화면 디자인 반영 및 화면 전환 구현

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#47]
## 🛠 Issue
시작 화면 디자인 반영 및 화면 전환 구현

## 📝 To-do
- [x] 연동 화면 디자인 반영
- [x] 시작 화면 디자인 반영
- [x] 화면 전환 구현
