### ISSUE TITLE
[Chore] 온보딩 뷰 디자인, UX 변경사항 반영 및 버튼 Gradient 추가

### ISSUE THREAD

**Issue by 0lynny** [Team-Umbba/Umbba-iOS#49]
## 🛠 Issue

온보딩 뷰 디자인 적용 및 버튼 Gradient 추가

## 📝 To-do

- [ ] CustomButton 디자인 적용
- [ ] 온보딩 뷰 디자인 적용
- [ ] UX 변경 사항 적용
