### ISSUE TITLE
[Feat] AnswerDetail 문답화면 구현하기 

### ISSUE THREAD

**Issue by yujin-00** [Team-Umbba/Umbba-iOS#52]
## 🛠 Issue

문답화면 구현하기 

## 📝 To-do

- [x] 문답화면에 맞는 네비게이션바 구현하기
- [x] 질문테마 스택뷰 구현하기
- [x] 상대방&나 질문과 답변 뷰 구현하기
- [ ] 하단 버튼 상황에 맞게 구현하기
