### ISSUE TITLE
[Feat] 초대하기 뷰 연결 및 플로우 구현

### ISSUE THREAD

**Issue by 0lynny** [Team-Umbba/Umbba-iOS#56]
## 🛠 Issue

- EntryView -> inviteView 로 이동 구현
- 초대코드 입력 정규식 수정
- 초대코드 errorLabel 관련 수정
- 초대 코드 입력 유저에 대한 분기처리를 통한 플로우 구현

## 📝 To-do

- [x] EntryView -> inviteView 로 이동 구현
- [x] 초대코드 입력 정규식 수정
- [x] 초대코드 errorLabel 관련 수정
- [x] 초대 코드 입력 유저에 대한 분기처리를 통한 플로우 구현
