### ISSUE TITLE
[Feat] 회원 탈퇴 뷰 구현

### ISSUE THREAD

**Issue by yujin-00** [Team-Umbba/Umbba-iOS#59]
## 🛠 Issue

회원 탈퇴 뷰 구현

## 📝 To-do

- [x] 회원 탈퇴 네비게이션바
- [x] 명언 UIView
- [x] 탈퇴하기 하단 버튼
- [x] 설정뷰 --> 계정 관리 --> 회원 탈퇴 플로우 연결
