### ISSUE TITLE
[Chore] 메인 화면 및 아카이빙 화면 이미지 레이아웃 수정

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#77]
## 🛠 Issue
메인 화면 및 아카이빙 화면 이미지 레이아웃 수정

## 📝 To-do

- [x] 메인 화면 SE 기기 이미지 추가 및 구현
- [x] 아카이빙 이미지 리소스 추가
- [x] 아카이빙 화면 이미지 레이아웃 수정
