### ISSUE TITLE
[Chore] 메인 화면 및 리스트 화면 레이아웃 수정

### ISSUE THREAD

**Issue by ahra1221** [Team-Umbba/Umbba-iOS#86]
## 🛠 Issue

메인 화면 및 리스트 화면 레이아웃 수정

## 📝 To-do

- [ ] 섹션 셀 is tapped 구현
- [x] 섹션 questionNumLabel 레이아웃 수정
- [x] 아카이빙 이미지 뷰 레이아웃 오류 수정
- [x] 아카이빙 뷰 네비게이션바 수정
- [x] 로티 뷰 스위프트 린트 수정
